### ISSUE TITLE
Switch to better data source

### ISSUE THREAD

**Issue by marcoow** [simplabs/breethe-server#104]
Unfortunately the data that we get from openaq.org is relatively poor. We should switch to a different data source as breethe only has real value if it shows good, up-to-date data.

**Comment by niklaslong** [comment]
Todo:

- [ ] CSV processing from EEA + test #191 
- [ ] implement source module + tests #200 
- [ ] refactor: use `{lat, lon}` instead of `lat, lon` throughout code base.
- [ ] refactor `Breethe` module to use `Source` + tests

**Comment by marhigh** [comment]
@marcoow will this increase which locations are supported? I get an error for anything outside of Europe.
